name: Contracts CI

on:
  push:
    branches:
      - release
  pull_request:
    paths:
      - 'packages/nouns-contracts/**'
      - 'packages/nouns-subgraph/**'
    branches:
      - '**'

env:
  NODE_OPTIONS: --max_old_space_size=5120

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn
      - run: yarn build
      - name: Run contract tests
        run: |
          cd packages/nouns-contracts
          yarn test
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge build
        run: |
          cd packages/nouns-contracts
          forge --version
          forge build --sizes
      - name: Run Forge tests
        run: |
          cd packages/nouns-contracts
          forge test -vvv --ffi
